name: Lint staged

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs: 
  check-lint-staged: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Check eslint and prettier
      run: npm run format
       